name: Publish Docker images

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  publish-docker-image-latest:
    runs-on: ubuntu-latest
    name: Publish Docker image from master branch
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out XBVR repo
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Push to Container Registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: coolmintchocolate
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: coolmintchocolate/xbvr
          push: true
          tags: latest

  publish-docker-image-dev:
    runs-on: ubuntu-latest
    name: Publish Docker image from dev branch
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out XBVR repo
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Push to Container Registry
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: coolmintchocolate
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: coolmintchocolate/xbvr
          push: true
          tags: dev
